"""Remover UniqueConstraint de CuentaMensual

Revision ID: 5db01c43dc31
Revises: 9245c28784de
Create Date: 2026-06-03 22:38:04.585834

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5db01c43dc31'
down_revision: Union[str, Sequence[str], None] = '9245c28784de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_client_month_year'), 'monthly_tabs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_client_month_year'), 'monthly_tabs', ['cliente_id', 'mes', 'anio'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
