"""Add Categoria and stock to Producto

Revision ID: e28dccca1b05
Revises: 5db01c43dc31
Create Date: 2026-06-13 02:19:50.631045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28dccca1b05'
down_revision: Union[str, Sequence[str], None] = '5db01c43dc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_nombre'), 'categories', ['nombre'], unique=True)
    op.add_column('products', sa.Column('stock_actual', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('categoria_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['categoria_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'categoria_id')
    op.drop_column('products', 'stock_actual')
    op.drop_index(op.f('ix_categories_nombre'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
