"""Agregar indices en foreign keys y filtros de periodo

Revision ID: eecfb048ffef
Revises: c7e51a9f3d02
Create Date: 2026-08-06 19:58:14.860594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecfb048ffef'
down_revision: Union[str, Sequence[str], None] = 'c7e51a9f3d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_losses_fecha_hora'), 'inventory_losses', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_inventory_losses_producto_id'), 'inventory_losses', ['producto_id'], unique=False)
    op.create_index('ix_monthly_tabs_cliente_periodo_estado', 'monthly_tabs', ['cliente_id', 'anio', 'mes', 'estado'], unique=False)
    op.create_index('ix_monthly_tabs_periodo', 'monthly_tabs', ['anio', 'mes'], unique=False)
    op.create_index(op.f('ix_products_categoria_id'), 'products', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_transactions_cuenta_mensual_id'), 'transactions', ['cuenta_mensual_id'], unique=False)
    op.create_index(op.f('ix_transactions_fecha_hora'), 'transactions', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_transactions_producto_id'), 'transactions', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_producto_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_fecha_hora'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_cuenta_mensual_id'), table_name='transactions')
    op.drop_index(op.f('ix_products_categoria_id'), table_name='products')
    op.drop_index('ix_monthly_tabs_periodo', table_name='monthly_tabs')
    op.drop_index('ix_monthly_tabs_cliente_periodo_estado', table_name='monthly_tabs')
    op.drop_index(op.f('ix_inventory_losses_producto_id'), table_name='inventory_losses')
    op.drop_index(op.f('ix_inventory_losses_fecha_hora'), table_name='inventory_losses')
    # ### end Alembic commands ###
